### ISSUE TITLE
error while compiling: 'waitpid' was not declared in this scope

### ISSUE THREAD

**Issue by krzysckh** [bcanozter/Simple-Cpp-Shell#1]
got error when i was trying to compile main.cpp

```
main.cpp: In function ‘int main()’:
main.cpp:211:21: error: ‘waitpid’ was not declared in this scope
                     waitpid(pid, &childStatus, 0);
                     ^~~~~~~
main.cpp:211:21: note: suggested alternative: ‘getpid’
                     waitpid(pid, &childStatus, 0);
                     ^~~~~~~
                     getpid
```

**Comment by bcanozter** [comment]
Hi,

Could you please include this `#include <sys/wait.h>` and try  again. Also I'm curious are you on MacOS or Linux?

`waitpid` seems to be under this here; [source](https://pubs.opengroup.org/onlinepubs/7990989799/xsh/syswait.h.html)

I will update if that is the case.

**Comment by krzysckh** [comment]
After including `<sys/wait.h>` everything compiles perfectly. Also i use Linux.
I think including this header will make it work on every unix-like operating system and not just MacOS.

Thanks for helping me!
